version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: accounty
      POSTGRES_USER: toucan
      POSTGRES_PASSWORD: password
    volumes:
      - accounty_pgdata:/var/lib/postgresql/data
    networks:
      - accounty_net
volumes:
  accounty_pgdata:
networks: 
  accounty_net: