// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf-spec/core.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// User in the system
type User struct {
	// Id of the user
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Username
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// Name
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Password
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// e-mail
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea9af7e0fea015fe, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// CreateUserRequest
type CreateUserRequest struct {
	// User to create
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea9af7e0fea015fe, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// CreateUserResponse
type CreateUserResponse struct {
	// Created user
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea9af7e0fea015fe, []int{2}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// ListUsersRequest is a request for listing users
type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea9af7e0fea015fe, []int{3}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

// ListUsersResponse contains the list of users found
type ListUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea9af7e0fea015fe, []int{4}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "github.com.io.toucasoft.accounty.v1.User")
	proto.RegisterType((*CreateUserRequest)(nil), "github.com.io.toucasoft.accounty.v1.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "github.com.io.toucasoft.accounty.v1.CreateUserResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "github.com.io.toucasoft.accounty.v1.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "github.com.io.toucasoft.accounty.v1.ListUsersResponse")
}

func init() { proto.RegisterFile("protobuf-spec/core.proto", fileDescriptor_ea9af7e0fea015fe) }

var fileDescriptor_ea9af7e0fea015fe = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x25, 0x69, 0xfa, 0xf1, 0xf5, 0x16, 0xc4, 0x0c, 0x8a, 0x21, 0xb8, 0x28, 0x71, 0x53, 0x17,
	0x4e, 0x68, 0xc5, 0x0a, 0x82, 0x08, 0xba, 0xd5, 0x4d, 0xaa, 0x1b, 0x77, 0xd3, 0xf4, 0x36, 0x0e,
	0x34, 0x33, 0x31, 0x33, 0x89, 0xba, 0x75, 0xef, 0x4a, 0xf0, 0x79, 0x7c, 0x07, 0x5f, 0xc1, 0x07,
	0x91, 0x4c, 0x6a, 0x5b, 0x74, 0xd3, 0xe2, 0x2e, 0xf7, 0x64, 0xce, 0xcf, 0x3d, 0x5c, 0xf0, 0xb2,
	0x5c, 0x6a, 0x39, 0x2a, 0x26, 0x07, 0x2a, 0xc3, 0x38, 0x8c, 0x65, 0x8e, 0xd4, 0x40, 0x64, 0x2f,
	0xe1, 0xfa, 0xae, 0x18, 0xd1, 0x58, 0xa6, 0x94, 0x4b, 0xaa, 0x65, 0x11, 0x33, 0x25, 0x27, 0x9a,
	0xb2, 0x38, 0x96, 0x85, 0xd0, 0x4f, 0xb4, 0xec, 0xf9, 0xbb, 0x89, 0x94, 0xc9, 0x14, 0x43, 0x96,
	0xf1, 0x90, 0x09, 0x21, 0x35, 0xd3, 0x5c, 0x0a, 0x55, 0x4b, 0x04, 0x8f, 0xe0, 0xdc, 0x28, 0xcc,
	0xc9, 0x06, 0xd8, 0x7c, 0xec, 0x59, 0x1d, 0xab, 0xdb, 0x88, 0x6c, 0x3e, 0x26, 0x3e, 0xfc, 0x2f,
	0x14, 0xe6, 0x82, 0xa5, 0xe8, 0xd9, 0x1d, 0xab, 0xdb, 0x8a, 0xe6, 0x33, 0x21, 0xe0, 0x18, 0xbc,
	0x61, 0x70, 0xf3, 0x5d, 0xbd, 0xcf, 0x98, 0x52, 0x0f, 0x32, 0x1f, 0x7b, 0x4e, 0xfd, 0xfe, 0x7b,
	0x26, 0x5b, 0xd0, 0xc4, 0x94, 0xf1, 0xa9, 0xd7, 0x34, 0x3f, 0xea, 0x21, 0x88, 0xc0, 0xbd, 0xc8,
	0x91, 0x69, 0xac, 0xfc, 0x23, 0xbc, 0x2f, 0x50, 0x69, 0x72, 0x0a, 0x4e, 0x65, 0x63, 0x82, 0xb4,
	0xfb, 0xfb, 0x74, 0x85, 0x05, 0xa9, 0xe1, 0x1b, 0x5a, 0x30, 0x04, 0xb2, 0xac, 0xa9, 0x32, 0x29,
	0x14, 0xfe, 0x55, 0x94, 0xc0, 0xe6, 0x25, 0x57, 0xba, 0x42, 0xd4, 0x2c, 0x67, 0x70, 0x0d, 0xee,
	0x12, 0x36, 0xf3, 0x39, 0x83, 0x66, 0x45, 0x50, 0x9e, 0xd5, 0x69, 0xac, 0x67, 0x54, 0xf3, 0xfa,
	0xef, 0x36, 0x6c, 0x57, 0xf3, 0x15, 0x13, 0x2c, 0xc1, 0x14, 0x85, 0x1e, 0x62, 0x5e, 0xf2, 0x18,
	0xc9, 0x9b, 0x05, 0xb0, 0xd8, 0x8c, 0x0c, 0x56, 0x92, 0xfe, 0x55, 0xaf, 0x7f, 0xbc, 0x36, 0xaf,
	0x5e, 0x2d, 0xd8, 0x79, 0xfe, 0xf8, 0x7c, 0xb5, 0xdd, 0xa0, 0x15, 0x96, 0xbd, 0xd0, 0x84, 0x3d,
	0x31, 0xe5, 0x90, 0x17, 0x0b, 0x5a, 0xf3, 0x26, 0xc8, 0xd1, 0x4a, 0xfa, 0x3f, 0xdb, 0xf4, 0x07,
	0xeb, 0xd2, 0x66, 0xa9, 0x5c, 0x93, 0xaa, 0x4d, 0x16, 0xa9, 0xce, 0xe1, 0xd6, 0xdc, 0xa9, 0x0a,
	0xcb, 0xde, 0xe8, 0x9f, 0x39, 0xf1, 0xc3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x52, 0xc9, 0x9a,
	0xf7, 0x41, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserManagementServiceClient is the client API for UserManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserManagementServiceClient interface {
	// Creates a new User in the system
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	// List the users in the system
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
}

type userManagementServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserManagementServiceClient(cc *grpc.ClientConn) UserManagementServiceClient {
	return &userManagementServiceClient{cc}
}

func (c *userManagementServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/github.com.io.toucasoft.accounty.v1.UserManagementService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManagementServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/github.com.io.toucasoft.accounty.v1.UserManagementService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserManagementServiceServer is the server API for UserManagementService service.
type UserManagementServiceServer interface {
	// Creates a new User in the system
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// List the users in the system
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
}

func RegisterUserManagementServiceServer(s *grpc.Server, srv UserManagementServiceServer) {
	s.RegisterService(&_UserManagementService_serviceDesc, srv)
}

func _UserManagementService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.io.toucasoft.accounty.v1.UserManagementService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManagementService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManagementServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.io.toucasoft.accounty.v1.UserManagementService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManagementServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserManagementService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.io.toucasoft.accounty.v1.UserManagementService",
	HandlerType: (*UserManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserManagementService_CreateUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _UserManagementService_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf-spec/core.proto",
}
